name: .NET Core

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.6.0
        with:
            dotnet-version: '5.0.100-preview.8'
  
      - name: Build (Release)
        run: dotnet build --configuration Release

      - name: Pack (Release)
        run: |
            dotnet pack src\AspNetCore.Unobtrusive.Ajax --configuration Release
            
      - name: Publish
        if: github.event_name == 'push'
        run: |      
            if ( "${{github.ref}}" -match "^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$" ) {
                dotnet nuget push src\AspNetCore.Unobtrusive.Ajax\bin\Release\*.nupkg -s nuget.org -k ${{secrets.NUGET_TOKEN}} --no-symbols true
            } else {
                echo "publish is only enabled by tagging with a release tag"
            }
